### ISSUE TITLE
Stable To-Do List

### ISSUE THREAD

**Issue by brian-patrick-3** [kyndryl-design-system/shidoka-applications#23]
For all four repositories.

- [x] Upgrade Storybook
- [x] Add open source license (MIT)
- [x] Change foundation to a peer dependency
- [x] Add migration guide for breaking changes since < 1.0.0-beta.30 (shidoka-applications)
- [ ] Update docs where beta is mentioned as the default release channel
- [ ] Merge `beta` to `main`
- [ ] Change default branches to `main` in each repo
